const UsersActionTypes = {
    CREATE_USER_START: 'CREATE_USER_START',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',
    READ_USERS_START: 'READ_USERS_START',
    READ_USERS_SUCCESS: 'READ_USERS_SUCCESS',
    READ_USERS_FAILURE: 'READ_USERS_FAILURE',
    READ_USER_START: 'READ_USER_START',
    READ_USER_SUCCESS: 'READ_USER_SUCCESS',
    READ_USER_FAILURE: 'READ_USER_FAILURE',
    UPDATE_USER_START: 'UPDATE_USER_START',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
    DELETE_USER_START: 'DELETE_USER_START',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',
}

export default UsersActionTypes;